const resourceLoader = {
    "Airi_home.skel": () => import('@skel/Airi_home.skel?binary'),
    'Airi_home.atlas': () => import('@atlas/Airi_home.atlas?raw'),
    'Airi_home.png': () => import('@png/Airi_home.png?binary'),
    'Airi_home2.png': () => import('@png/Airi_home2.png?binary'),

    'Akane_home.skel': () => import('@skel/Akane_home.skel?binary'),
    'Akane_home.atlas': () => import('@atlas/Akane_home.atlas?raw'),
    'Akane_home.png': () => import('@png/Akane_home.png?binary'),

    'akari_bg.skel': () => import('@skel/akari_bg.skel?binary'),
    'akari_home.skel': () => import('@skel/akari_home.skel?binary'),
    'akari_scene.skel': () => import('@skel/akari_scene.skel?binary'),
    'akari_bg.atlas': () => import('@atlas/akari_bg.atlas?raw'),
    'akari_home.atlas': () => import('@atlas/akari_home.atlas?raw'),
    'akari_scene.atlas': () => import('@atlas/akari_scene.atlas?raw'),
    'akari_bg.png': () => import('@png/akari_bg.png?binary'),
    'akari_home.png': () => import('@png/akari_home.png?binary'),
    'akari_scene.png': () => import('@png/akari_scene.png?binary'),

    'Aru_home.skel': () => import('@skel/Aru_home.skel?binary'),
    'Aru_scene.skel': () => import('@skel/Aru_scene.skel?binary'),
    'Aru_home.atlas': () => import('@atlas/Aru_home.atlas?raw'),
    'Aru_scene.atlas': () => import('@atlas/Aru_scene.atlas?raw'),
    'Aru_scene.png': () => import('@png/Aru_scene.png?binary'),
    'Aru_home.png': () => import('@png/Aru_home.png?binary'),
    'Aru_home2.png': () => import('@png/Aru_home2.png?binary'),
    'Aru_home3.png': () => import('@png/Aru_home3.png?binary'),

    'Asuna_home.skel': () => import('@skel/Asuna_home.skel?binary'),
    'Asuna_home.atlas': () => import('@atlas/Asuna_home.atlas?raw'),
    'Asuna_home.png': () => import('@png/Asuna_home.png?binary'),
    'Asuna_home2.png': () => import('@png/Asuna_home2.png?binary'),

    'Ayane_home.skel': () => import('@skel/Ayane_home.skel?binary'),
    'Ayane_home.atlas': () => import('@atlas/Ayane_home.atlas?raw'),
    'Ayane_home.png': () => import('@png/Ayane_home.png?binary'),
    'Ayane_home2.png': () => import('@png/Ayane_home2.png?binary'),
    'Ayane_home3.png': () => import('@png/Ayane_home3.png?binary'),

    'Chinatsu_home.skel': () => import('@skel/Chinatsu_home.skel?binary'),
    'Chinatsu_home.atlas': () => import('@atlas/Chinatsu_home.atlas?raw'),
    'Chinatsu_home.png': () => import('@png/Chinatsu_home.png?binary'),
    'Chinatsu_home_2.png': () => import('@png/Chinatsu_home_2.png?binary'),

    'Chise_home.skel': () => import('@skel/Chise_home.skel?binary'),
    'Chise_home.atlas': () => import('@atlas/Chise_home.atlas?raw'),
    'Chise_home.png': () => import('@png/Chise_home.png?binary'),
    'Chise_home2.png': () => import('@png/Chise_home2.png?binary'),

    'Eimi_home.skel': () => import('@skel/Eimi_home.skel?binary'),
    'Eimi_home.atlas': () => import('@atlas/Eimi_home.atlas?raw'),
    'Eimi_home.png': () => import('@png/Eimi_home.png?binary'),
    'Eimi_home2.png': () => import('@png/Eimi_home2.png?binary'),

    'Fuuka_home.skel': () => import('@skel/Fuuka_home.skel?binary'),
    'Fuuka_Scene.skel': () => import('@skel/Fuuka_Scene.skel?binary'),
    'Fuuka_home.atlas': () => import('@atlas/Fuuka_home.atlas?raw'),
    'Fuuka_Scene.atlas': () => import('@atlas/Fuuka_Scene.atlas?raw'),
    'Fuuka_Scene.png': () => import('@png/Fuuka_Scene.png?binary'),
    'Fuuka_home.png': () => import('@png/Fuuka_home.png?binary'),
    'Fuuka_home2.png': () => import('@png/Fuuka_home2.png?binary'),

    'Hanae_home.skel': () => import('@skel/Hanae_home.skel?binary'),
    'Hanae_home.atlas': () => import('@atlas/Hanae_home.atlas?raw'),
    'Hanae_home.png': () => import('@png/Hanae_home.png?binary'),
    'Hanae_home2.png': () => import('@png/Hanae_home2.png?binary'),

    'Hare_home.skel': () => import('@skel/Hare_home.skel?binary'),
    'Hare_home.atlas': () => import('@atlas/Hare_home.atlas?raw'),
    'Hare_home.png': () => import('@png/Hare_home.png?binary'),
    'Hare_home2.png': () => import('@png/Hare_home2.png?binary'),

    'Haruka_home.skel': () => import('@skel/Haruka_home.skel?binary'),
    'Haruka_home.atlas': () => import('@atlas/Haruka_home.atlas?raw'),
    'Haruka_home.png': () => import('@png/Haruka_home.png?binary'),
    'Haruka_home2.png': () => import('@png/Haruka_home2.png?binary'),

    'Haruna_home.skel': () => import('@skel/Haruna_home.skel?binary'),
    'Haruna_home.atlas': () => import('@atlas/Haruna_home.atlas?raw'),
    'Haruna_home.png': () => import('@png/Haruna_home.png?binary'),
    'Haruna_home2.png': () => import('@png/Haruna_home2.png?binary'),

    'Hasumi_home.skel': () => import('@skel/Hasumi_home.skel?binary'),
    'Hasumi_home.atlas': () => import('@atlas/Hasumi_home.atlas?raw'),
    'Hasumi_home.png': () => import('@png/Hasumi_home.png?binary'),
    'Hasumi_home2.png': () => import('@png/Hasumi_home2.png?binary'),

    'Hibiki_home.skel': () => import('@skel/Hibiki_home.skel?binary'),
    'Hibiki_home.atlas': () => import('@atlas/Hibiki_home.atlas?raw'),
    'Hibiki_home.png': () => import('@png/Hibiki_home.png?binary'),
    'Hibiki_home2.png': () => import('@png/Hibiki_home2.png?binary'),

    'Hihumi_home.skel': () => import('@skel/Hihumi_home.skel?binary'),
    'Hihumi_home.atlas': () => import('@atlas/Hihumi_home.atlas?raw'),
    'Hihumi_home.png': () => import('@png/Hihumi_home.png?binary'),
    'Hihumi_home_2.png': () => import('@png/Hihumi_home_2.png?binary'),

    'Hina_home.skel': () => import('@skel/Hina_home.skel?binary'),
    'Hina_home.atlas': () => import('@atlas/Hina_home.atlas?raw'),
    'Hina_home.png': () => import('@png/Hina_home.png?binary'),
    'Hina_home2.png': () => import('@png/Hina_home2.png?binary'),
    'Hina_home3.png': () => import('@png/Hina_home3.png?binary'),

    'Hoshino_home.skel': () => import('@skel/Hoshino_home.skel?binary'),
    'Hoshino_home_background.skel': () => import('@skel/Hoshino_home_background.skel?binary'),
    'Hoshino_home.atlas': () => import('@atlas/Hoshino_home.atlas?raw'),
    'Hoshino_home_background.atlas': () => import('@atlas/Hoshino_home_background.atlas?raw'),
    'Hoshino_home.png': () => import('@png/Hoshino_home.png?binary'),
    'Hoshino_home_background.png': () => import('@png/Hoshino_home_background.png?binary'),
    'Hoshino_home_background2.png': () => import('@png/Hoshino_home_background2.png?binary'),

    'Iori_home.skel': () => import('@skel/Iori_home.skel?binary'),
    'Iori_home.atlas': () => import('@atlas/Iori_home.atlas?raw'),
    'Iori_home.png': () => import('@png/Iori_home.png?binary'),
    'Iori_home2.png': () => import('@png/Iori_home2.png?binary'),

    'Izumi_home.skel': () => import('@skel/Izumi_home.skel?binary'),
    'Izumi_home.atlas': () => import('@atlas/Izumi_home.atlas?raw'),
    'Izumi_home.png': () => import('@png/Izumi_home.png?binary'),
    'Izumi_home2.png': () => import('@png/Izumi_home2.png?binary'),

    'Zunko_home.skel': () => import('@skel/Zunko_home.skel?binary'),
    'Zunko_home.atlas': () => import('@atlas/Zunko_home.atlas?raw'),
    'Zunko_home.png': () => import('@png/Zunko_home.png?binary'),
    'Zunko_home2.png': () => import('@png/Zunko_home2.png?binary'),

    'Juri_home.skel': () => import('@skel/Juri_home.skel?binary'),
    'Juri_home.atlas': () => import('@atlas/juri_home.atlas?raw'),//emm,是的,并没有写错
    'Juri_home.png': () => import('@png/Juri_home.png?binary'),
    'Juri_home2.png': () => import('@png/Juri_home2.png?binary'),
    'Juri_home3.png': () => import('@png/Juri_home3.png?binary'),

    'Karin_home.skel': () => import('@skel/Karin_home.skel?binary'),
    'Karin_home.atlas': () => import('@atlas/Karin_home.atlas?raw'),
    'Karin_home.png': () => import('@png/Karin_home.png?binary'),

    'Kayoko_home.skel': () => import('@skel/Kayoko_home.skel?binary'),
    'Kayoko_home.atlas': () => import('@atlas/Kayoko_home.atlas?raw'),
    'Kayoko_home.png': () => import('@png/Kayoko_home.png?binary'),
    'Kayoko_home2.png': () => import('@png/Kayoko_home2.png?binary'),

    'Kotama_home.skel': () => import('@skel/Kotama_home.skel?binary'),
    'Kotama_home.atlas': () => import('@atlas/Kotama_home.atlas?raw'),
    'Kotama_home.png': () => import('@png/Kotama_home.png?binary'),
    'Kotama_home2.png': () => import('@png/Kotama_home2.png?binary'),

    'Kotori_home.skel': () => import('@skel/Kotori_home.skel?binary'),
    'Kotori_home.atlas': () => import('@atlas/Kotori_home.atlas?raw'),
    'Kotori_home.png': () => import('@png/Kotori_home.png?binary'),
    'Kotori_home2.png': () => import('@png/Kotori_home2.png?binary'),

    
    'Maki_home.skel': () => import('@skel/Maki_home.skel?binary'),
    'Maki_home.atlas': () => import('@atlas/Maki_home.atlas?raw'),
    'Maki_home2.png': () => import('@png/Maki_home2.png?binary'),
    'Maki_home.png': () => import('@png/Maki_home.png?binary'),

    'Mutsuki_home.skel': () => import('@skel/Mutsuki_home.skel?binary'),
    'Mutsuki_home.atlas': () => import('@atlas/Mutsuki_home.atlas?raw'),
    'Mutsuki_home2.png': () => import('@png/Mutsuki_home2.png?binary'),
    'Mutsuki_home.png': () => import('@png/Mutsuki_home.png?binary'),

    'Neru_home.skel': () => import('@skel/Neru_home.skel?binary'),
    'Neru_home.atlas': () => import('@atlas/Neru_home.atlas?raw'),
    'Neru_home3.png': () => import('@png/Neru_home3.png?binary'),
    'Neru_home2.png': () => import('@png/Neru_home2.png?binary'),
    'Neru_home.png': () => import('@png/Neru_home.png?binary'),

    'Nonomi_home.skel': () => import('@skel/Nonomi_home.skel?binary'),
    'Nonomi_home.atlas': () => import('@atlas/Nonomi_home.atlas?raw'),
    'Nonomi_home2.png': () => import('@png/Nonomi_home2.png?binary'),
    'Nonomi_home.png': () => import('@png/Nonomi_home.png?binary'),

    'Pina_home.skel': () => import('@skel/Pina_home.skel?binary'),
    'Pina_home.atlas': () => import('@atlas/Pina_home.atlas?raw'),
    'Pina_home2.png': () => import('@png/Pina_home2.png?binary'),
    'Pina_home.png': () => import('@png/Pina_home.png?binary'),

    'Saya_home.skel': () => import('@skel/Saya_home.skel?binary'),
    'Saya_home.atlas': () => import('@atlas/Saya_home.atlas?raw'),
    'Saya_home2.png': () => import('@png/Saya_home2.png?binary'),
    'Saya_home.png': () => import('@png/Saya_home.png?binary'),

    'Serika_home.skel': () => import('@skel/Serika_home.skel?binary'),
    'Serika_home.atlas': () => import('@atlas/Serika_home.atlas?raw'),
    'Serika_home_3.png': () => import('@png/Serika_home_3.png?binary'),
    'Serika_home_2.png': () => import('@png/Serika_home_2.png?binary'),
    'Serika_home.png': () => import('@png/Serika_home.png?binary'),

    'serina_home.skel': () => import('@skel/serina_home.skel?binary'),
    'serina_home.atlas': () => import('@atlas/serina_home.atlas?raw'),
    'serina_home2.png': () => import('@png/serina_home2.png?binary'),
    'serina_home.png': () => import('@png/serina_home.png?binary'),

    'Shimiko_home.skel': () => import('@skel/Shimiko_home.skel?binary'),
    'Shimiko_home.atlas': () => import('@atlas/Shimiko_home.atlas?raw'),
    'Shimiko_home3.png': () => import('@png/Shimiko_home3.png?binary'),
    'Shimiko_home2.png': () => import('@png/Shimiko_home2.png?binary'),
    'Shimiko_home.png': () => import('@png/Shimiko_home.png?binary'),

    'Shiroko_home.skel': () => import('@skel/Shiroko_home.skel?binary'),
    'Shiroko_home.atlas': () => import('@atlas/Shiroko_home.atlas?raw'),
    'Shiroko_home2.png': () => import('@png/Shiroko_home2.png?binary'),
    'Shiroko_home.png': () => import('@png/Shiroko_home.png?binary'),

    'Shun_home.skel': () => import('@skel/Shun_home.skel?binary'),
    'Shun_home.atlas': () => import('@atlas/Shun_home.atlas?raw'),
    'Shun_home2.png': () => import('@png/Shun_home2.png?binary'),
    'Shun_home.png': () => import('@png/Shun_home.png?binary'),

    'Sumire_home.skel': () => import('@skel/Sumire_home.skel?binary'),
    'Sumire_home.atlas': () => import('@atlas/Sumire_home.atlas?raw'),
    'Sumire_home.png': () => import('@png/Sumire_home.png?binary'),

    'Suzumi_home.skel': () => import('@skel/Suzumi_home.skel?binary'),
    'Suzumi_home.atlas': () => import('@atlas/Suzumi_home.atlas?raw'),
    'Suzumi_home2.png': () => import('@png/Suzumi_home2.png?binary'),
    'Suzumi_home.png': () => import('@png/Suzumi_home.png?binary'),

    'Tsubaki_home.skel': () => import('@skel/Tsubaki_home.skel?binary'),
    'Tsubaki_home.atlas': () => import('@atlas/Tsubaki_home.atlas?raw'),
    'Tsubaki_home2.png': () => import('@png/Tsubaki_home2.png?binary'),
    'Tsubaki_home.png': () => import('@png/Tsubaki_home.png?binary'),

    'Tsurugi_home.skel': () => import('@skel/Tsurugi_home.skel?binary'),
    'Tsurugi_home.atlas': () => import('@atlas/Tsurugi_home.atlas?raw'),
    'Tsurugi_home3.png': () => import('@png/Tsurugi_home3.png?binary'),
    'Tsurugi_home2.png': () => import('@png/Tsurugi_home2.png?binary'),
    'Tsurugi_home.png': () => import('@png/Tsurugi_home.png?binary'),

    'Utaha_home.skel': () => import('@skel/Utaha_home.skel?binary'),
    'Utaha_home.atlas': () => import('@atlas/Utaha_home.atlas?raw'),
    'Utaha_home2.png': () => import('@png/Utaha_home2.png?binary'),
    'Utaha_home.png': () => import('@png/Utaha_home.png?binary'),

    'Yoshimi_home.skel': () => import('@skel/Yoshimi_home.skel?binary'),
    'Yoshimi_home.atlas': () => import('@atlas/Yoshimi_home.atlas?raw'),
    'Yoshimi_home2.png': () => import('@png/Yoshimi_home2.png?binary'),
    'Yoshimi_home.png': () => import('@png/Yoshimi_home.png?binary'),

    'Yuuka_home.skel': () => import('@skel/Yuuka_home.skel?binary'),
    'Yuuka_home.atlas': () => import('@atlas/Yuuka_home.atlas?raw'),
    'Yuuka_home2.png': () => import('@png/Yuuka_home2.png?binary'),
    'Yuuka_home.png': () => import('@png/Yuuka_home.png?binary'),

    'Mashiro_home.skel': () => import('@skel/Mashiro_home.skel?binary'),
    'Mashiro_home.atlas': () => import('@atlas/Mashiro_home.atlas?raw'),
    'Mashiro_home2.png': () => import('@png/Mashiro_home2.png?binary'),
    'Mashiro_home.png': () => import('@png/Mashiro_home.png?binary'),

    'Izuna_home.skel': () => import('@skel/Izuna_home.skel?binary'),
    'Izuna_home.atlas': () => import('@atlas/Izuna_home.atlas?raw'),
    'Izuna_home2.png': () => import('@png/Izuna_home2.png?binary'),
    'Izuna_home.png': () => import('@png/Izuna_home.png?binary'),

    'Shizuko_home.skel': () => import('@skel/Shizuko_home.skel?binary'),
    'Shizuko_home.atlas': () => import('@atlas/Shizuko_home.atlas?raw'),
    'Shizuko_home2.png': () => import('@png/Shizuko_home2.png?binary'),
    'Shizuko_home.png': () => import('@png/Shizuko_home.png?binary'),

    'Aris_home.skel': () => import('@skel/Aris_home.skel?binary'),
    'Aris_home.atlas': () => import('@atlas/Aris_home.atlas?raw'),
    'Aris_home2.png': () => import('@png/Aris_home2.png?binary'),
    'Aris_home.png': () => import('@png/Aris_home.png?binary'),

    'Midori_home.skel': () => import('@skel/Midori_home.skel?binary'),
    'Midori_home.atlas': () => import('@atlas/Midori_home.atlas?raw'),
    'Midori_home2.png': () => import('@png/Midori_home2.png?binary'),
    'Midori_home.png': () => import('@png/Midori_home.png?binary'),

    'Momoi_Scene.skel': () => import('@skel/Momoi_Scene.skel?binary'),
    'Momoi_home.skel': () => import('@skel/Momoi_home.skel?binary'),
    'Momoi_Scene.atlas': () => import('@atlas/Momoi_Scene.atlas?raw'),
    'Momoi_home.atlas': () => import('@atlas/Momoi_home.atlas?raw'),
    'Momoi_Scene.png': () => import('@png/Momoi_Scene.png?binary'),
    'Momoi_home2.png': () => import('@png/Momoi_home2.png?binary'),
    'Momoi_home.png': () => import('@png/Momoi_home.png?binary'),

    'Cherino_home.skel': () => import('@skel/Cherino_home.skel?binary'),
    'Cherino_home.atlas': () => import('@atlas/Cherino_home.atlas?raw'),
    'Cherino_home2.png': () => import('@png/Cherino_home2.png?binary'),
    'Cherino_home.png': () => import('@png/Cherino_home.png?binary'),

    'Nodoka_home.skel': () => import('@skel/Nodoka_home.skel?binary'),
    'Nodoka_home.atlas': () => import('@atlas/Nodoka_home.atlas?raw'),
    'Nodoka_home2.png': () => import('@png/Nodoka_home2.png?binary'),
    'Nodoka_home.png': () => import('@png/Nodoka_home.png?binary'),

    'Yuzu_home.skel': () => import('@skel/Yuzu_home.skel?binary'),
    'yuzu_bg.skel': () => import('@skel/yuzu_bg.skel?binary'),
    'Yuzu_home.atlas': () => import('@atlas/Yuzu_home.atlas?raw'),
    'yuzu_bg.atlas': () => import('@atlas/yuzu_bg.atlas?raw'),
    'Yuzu_home.png': () => import('@png/Yuzu_home.png?binary'),
    'yuzu_bg.png': () => import('@png/yuzu_bg.png?binary'),

    'Azusa_home.skel': () => import('@skel/Azusa_home.skel?binary'),
    'Azusa_home.atlas': () => import('@atlas/Azusa_home.atlas?raw'),
    'Azusa_home2.png': () => import('@png/Azusa_home2.png?binary'),
    'Azusa_home.png': () => import('@png/Azusa_home.png?binary'),

    'Hanako_home.skel': () => import('@skel/Hanako_home.skel?binary'),
    'Hanako_home.atlas': () => import('@atlas/Hanako_home.atlas?raw'),
    'Hanako_home2.png': () => import('@png/Hanako_home2.png?binary'),
    'Hanako_home.png': () => import('@png/Hanako_home.png?binary'),

    'Koharu_home.skel': () => import('@skel/Koharu_home.skel?binary'),
    'Koharu_home.atlas': () => import('@atlas/Koharu_home.atlas?raw'),
    'Koharu_home2.png': () => import('@png/Koharu_home2.png?binary'),
    'Koharu_home.png': () => import('@png/Koharu_home.png?binary'),

    'Azusa_swimsuit_home.skel': () => import('@skel/Azusa_swimsuit_home.skel?binary'),
    'Azusa_swimsuit_home.atlas': () => import('@atlas/Azusa_swimsuit_home.atlas?raw'),
    'Azusa_swimsuit_home2.png': () => import('@png/Azusa_swimsuit_home2.png?binary'),
    'Azusa_swimsuit_home.png': () => import('@png/Azusa_swimsuit_home.png?binary'),

    'Mashiro_swimsuit_home.skel': () => import('@skel/Mashiro_swimsuit_home.skel?binary'),
    'Mashiro_swimsuit_home.atlas': () => import('@atlas/Mashiro_swimsuit_home.atlas?raw'),
    'Mashiro_swimsuit_home2.png': () => import('@png/Mashiro_swimsuit_home2.png?binary'),
    'Mashiro_swimsuit_home.png': () => import('@png/Mashiro_swimsuit_home.png?binary'),

    'CH0060_home.skel': () => import('@skel/CH0060_home.skel?binary'),
    'CH0060_home.atlas': () => import('@atlas/CH0060_home.atlas?raw'),
    'CH0060_home.png': () => import('@png/CH0060_home.png?binary'),

    'CH0058_home.skel': () => import('@skel/CH0058_home.skel?binary'),
    'CH0058_home.atlas': () => import('@atlas/CH0058_home.atlas?raw'),
    'CH0058_home2.png': () => import('@png/CH0058_home2.png?binary'),
    'CH0058_home.png': () => import('@png/CH0058_home.png?binary'),

    'CH0063_home.skel': () => import('@skel/CH0063_home.skel?binary'),
    'CH0063_home.atlas': () => import('@atlas/CH0063_home.atlas?raw'),
    'CH0063_home2.png': () => import('@png/CH0063_home2.png?binary'),
    'CH0063_home.png': () => import('@png/CH0063_home.png?binary'),

    'CH0064_home.skel': () => import('@skel/CH0064_home.skel?binary'),
    'CH0064_home.atlas': () => import('@atlas/CH0064_home.atlas?raw'),
    'CH0064_home2.png': () => import('@png/CH0064_home2.png?binary'),
    'CH0064_home.png': () => import('@png/CH0064_home.png?binary'),

    'Izumi_swimsuit_home.skel': () => import('@skel/Izumi_swimsuit_home.skel?binary'),
    'Izumi_swimsuit_home.atlas': () => import('@atlas/Izumi_swimsuit_home.atlas?raw'),
    'Izumi_swimsuit_home2.png': () => import('@png/Izumi_swimsuit_home2.png?binary'),
    'Izumi_swimsuit_home.png': () => import('@png/Izumi_swimsuit_home.png?binary'),

    'Shiroko_ridingsuit_home.skel': () => import('@skel/Shiroko_ridingsuit_home.skel?binary'),
    'Shiroko_ridingsuit_home.atlas': () => import('@atlas/Shiroko_ridingsuit_home.atlas?raw'),
    'Shiroko_ridingsuit_home2.png': () => import('@png/Shiroko_ridingsuit_home2.png?binary'),
    'Shiroko_ridingsuit_home.png': () => import('@png/Shiroko_ridingsuit_home.png?binary'),


    'CH0066_home.skel': () => import('@skel/CH0066_home.skel?binary'),
    'CH0066_home.atlas': () => import('@atlas/CH0066_home.atlas?raw'),
    'CH0066_home2.png': () => import('@png/CH0066_home2.png?binary'),
    'CH0066_home.png': () => import('@png/CH0066_home.png?binary'),

    'Saya_casual_home.skel': () => import('@skel/Saya_casual_home.skel?binary'),
    'Saya_casual_home.atlas': () => import('@atlas/Saya_casual_home.atlas?raw'),
    'Saya_casual_home2.png': () => import('@png/Saya_casual_home2.png?binary'),
    'Saya_casual_home.png': () => import('@png/Saya_casual_home.png?binary'),

    'CH0100_home.skel': () => import('@skel/CH0100_home.skel?binary'),
    'CH0100_home.atlas': () => import('@atlas/CH0100_home.atlas?raw'),
    'CH0100_home_2.png': () => import('@png/CH0100_home_2.png?binary'),
    'CH0100_home.png': () => import('@png/CH0100_home.png?binary'),

    'CH0101_home.skel': () => import('@skel/CH0101_home.skel?binary'),
    'CH0101_home.atlas': () => import('@atlas/CH0101_home.atlas?raw'),
    'CH0101_home2.png': () => import('@png/CH0101_home2.png?binary'),
    'CH0101_home.png': () => import('@png/CH0101_home.png?binary'),

    'CH0098_home.skel': () => import('@skel/CH0098_home.skel?binary'),
    'CH0098_home.atlas': () => import('@atlas/CH0098_home.atlas?raw'),
    'CH0098_home2.png': () => import('@png/CH0098_home2.png?binary'),
    'CH0098_home.png': () => import('@png/CH0098_home.png?binary'),


    'CH0155_home.skel': () => import('@skel/CH0155_home.skel?binary'),
    'CH0155_home.atlas': () => import('@atlas/CH0155_home.atlas?raw'),
    'CH0155_home2.png': () => import('@png/CH0155_home2.png?binary'),
    'CH0155_home.png': () => import('@png/CH0155_home.png?binary'),

    'CH9999_home.skel': () => import('@skel/CH9999_home.skel?binary'),
    'CH9999_home.atlas': () => import('@atlas/CH9999_home.atlas?raw'),
    'CH9999_home3.png': () => import('@png/CH9999_home3.png?binary'),
    'CH9999_home2.png': () => import('@png/CH9999_home2.png?binary'),
    'CH9999_home.png': () => import('@png/CH9999_home.png?binary'),

    'Ako_home.skel': () => import('@skel/Ako_home.skel?binary'),
    'Ako_home.atlas': () => import('@atlas/Ako_home.atlas?raw'),
    'Ako_home2.png': () => import('@png/Ako_home2.png?binary'),
    'Ako_home.png': () => import('@png/Ako_home.png?binary'),

    'CH0164_home.skel': () => import('@skel/CH0164_home.skel?binary'),
    'CH0164_home.atlas': () => import('@atlas/CH0164_home.atlas?raw'),
    'CH0164_home2.png': () => import('@png/CH0164_home2.png?binary'),
    'CH0164_home.png': () => import('@png/CH0164_home.png?binary'),

    'CH0163_home.skel': () => import('@skel/CH0163_home.skel?binary'),
    'CH0163_home.atlas': () => import('@atlas/CH0163_home.atlas?raw'),
    'CH0163_home2.png': () => import('@png/CH0163_home2.png?binary'),
    'CH0163_home.png': () => import('@png/CH0163_home.png?binary'),

    'Tomoe_home.skel': () => import('@skel/Tomoe_home.skel?binary'),
    'Tomoe_home.atlas': () => import('@atlas/Tomoe_home.atlas?raw'),
    'Tomoe_home2.png': () => import('@png/Tomoe_home2.png?binary'),
    'Tomoe_home.png': () => import('@png/Tomoe_home.png?binary'),

    'CH0165_home.skel': () => import('@skel/CH0165_home.skel?binary'),
    'CH0165_home.atlas': () => import('@atlas/CH0165_home.atlas?raw'),
    'CH0165_home2.png': () => import('@png/CH0165_home2.png?binary'),
    'CH0165_home.png': () => import('@png/CH0165_home.png?binary'),

    'Aru_newyear_home.skel': () => import('@skel/Aru_newyear_home.skel?binary'),
    'Aru_newyear_home.atlas': () => import('@atlas/Aru_newyear_home.atlas?raw'),
    'Aru_newyear_home3.png': () => import('@png/Aru_newyear_home3.png?binary'),
    'Aru_newyear_home2.png': () => import('@png/Aru_newyear_home2.png?binary'),
    'Aru_newyear_home.png': () => import('@png/Aru_newyear_home.png?binary'),

    'mutsuki_newyear_home.skel': () => import('@skel/mutsuki_newyear_home.skel?binary'),
    'mutsuki_newyear_home.atlas': () => import('@atlas/mutsuki_newyear_home.atlas?raw'),
    'mutsuki_newyear_home3.png': () => import('@png/mutsuki_newyear_home3.png?binary'),
    'mutsuki_newyear_home2.png': () => import('@png/mutsuki_newyear_home2.png?binary'),
    'mutsuki_newyear_home.png': () => import('@png/mutsuki_newyear_home.png?binary'),

    'Serika_Newyear_home.skel': () => import('@skel/Serika_Newyear_home.skel?binary'),
    'Serika_Newyear_home.atlas': () => import('@atlas/Serika_Newyear_home.atlas?raw'),
    'Serika_Newyear_home2.png': () => import('@png/Serika_Newyear_home2.png?binary'),
    'Serika_Newyear_home.png': () => import('@png/Serika_Newyear_home.png?binary'),

    'CH0141_home.skel': () => import('@skel/CH0141_home.skel?binary'),
    'CH0141_home.atlas': () => import('@atlas/CH0141_home.atlas?raw'),
    'CH0141_home_2.png': () => import('@png/CH0141_home_2.png?binary'),
    'CH0141_home.png': () => import('@png/CH0141_home.png?binary'),

    'Wakamo_Scene_0.skel': () => import('@skel/Wakamo_Scene_0.skel?binary'),
    'Wakamo_home.skel': () => import('@skel/Wakamo_home.skel?binary'),
    'Wakamo_Scene_0.atlas': () => import('@atlas/Wakamo_Scene_0.atlas?raw'),
    'Wakamo_home.atlas': () => import('@atlas/Wakamo_home.atlas?raw'),
    'Wakamo_Scene_04.png': () => import('@png/Wakamo_Scene_04.png?binary'),
    'Wakamo_Scene_03.png': () => import('@png/Wakamo_Scene_03.png?binary'),
    'Wakamo_Scene_02.png': () => import('@png/Wakamo_Scene_02.png?binary'),
    'Wakamo_Scene_0.png': () => import('@png/Wakamo_Scene_0.png?binary'),
    'Wakamo_home2.png': () => import('@png/Wakamo_home2.png?binary'),
    'Wakamo_home.png': () => import('@png/Wakamo_home.png?binary'),

    'CH0160_home.skel': () => import('@skel/CH0160_home.skel?binary'),
    'CH0160_home.atlas': () => import('@atlas/CH0160_home.atlas?raw'),
    'CH0160_home2.png': () => import('@png/CH0160_home2.png?binary'),
    'CH0160_home.png': () => import('@png/CH0160_home.png?binary'),


    'Mimori_home.skel': () => import('@skel/Mimori_home.skel?binary'),
    'Mimori_home.atlas': () => import('@atlas/Mimori_home.atlas?raw'),
    'Mimori_home2.png': () => import('@png/Mimori_home2.png?binary'),
    'Mimori_home.png': () => import('@png/Mimori_home.png?binary'),

    'Hinata_home.skel': () => import('@skel/Hinata_home.skel?binary'),
    'Hinata_home.atlas': () => import('@atlas/Hinata_home.atlas?raw'),
    'Hinata_home2.png': () => import('@png/Hinata_home2.png?binary'),
    'Hinata_home.png': () => import('@png/Hinata_home.png?binary'),

    'CH0169_home.skel': () => import('@skel/CH0169_home.skel?binary'),
    'CH0169_home.atlas': () => import('@atlas/CH0169_home.atlas?raw'),
    'CH0169_home2.png': () => import('@png/CH0169_home2.png?binary'),
    'CH0169_home.png': () => import('@png/CH0169_home.png?binary'),

    'Marina_home.skel': () => import('@skel/Marina_home.skel?binary'),
    'Marina_home.atlas': () => import('@atlas/Marina_home.atlas?raw'),
    'Marina_home2.png': () => import('@png/Marina_home2.png?binary'),
    'Marina_home.png': () => import('@png/Marina_home.png?binary'),

    'Miyako_home.skel': () => import('@skel/Miyako_home.skel?binary'),
    'Miyako_home.atlas': () => import('@atlas/Miyako_home.atlas?raw'),
    'Miyako_home2.png': () => import('@png/Miyako_home2.png?binary'),
    'Miyako_home.png': () => import('@png/Miyako_home.png?binary'),

    'CH0144_home.skel': () => import('@skel/CH0144_home.skel?binary'),
    'CH0144_home.atlas': () => import('@atlas/CH0144_home.atlas?raw'),
    'CH0144_home2.png': () => import('@png/CH0144_home2.png?binary'),
    'CH0144_home.png': () => import('@png/CH0144_home.png?binary'),

    'CH0145_home.skel': () => import('@skel/CH0145_home.skel?binary'),
    'CH0145_home.atlas': () => import('@atlas/CH0145_home.atlas?raw'),
    'CH0145_home2.png': () => import('@png/CH0145_home2.png?binary'),
    'CH0145_home.png': () => import('@png/CH0145_home.png?binary'),

    'CH0156_home.skel': () => import('@skel/CH0156_home.skel?binary'),
    'CH0156_home.atlas': () => import('@atlas/CH0156_home.atlas?raw'),
    'CH0156_home2.png': () => import('@png/CH0156_home2.png?binary'),
    'CH0156_home.png': () => import('@png/CH0156_home.png?binary'),

    'Kaede_home.skel': () => import('@skel/Kaede_home.skel?binary'),
    'Kaede_home.atlas': () => import('@atlas/Kaede_home.atlas?raw'),
    'Kaede_home2.png': () => import('@png/Kaede_home2.png?binary'),
    'Kaede_home.png': () => import('@png/Kaede_home.png?binary'),

    'CH0113_home.skel': () => import('@skel/CH0113_home.skel?binary'),
    'CH0113_home.atlas': () => import('@atlas/CH0113_home.atlas?raw'),
    'CH0113_home3.png': () => import('@png/CH0113_home3.png?binary'),
    'CH0113_home2.png': () => import('@png/CH0113_home2.png?binary'),
    'CH0113_home.png': () => import('@png/CH0113_home.png?binary'),

    'CH0114_home.skel': () => import('@skel/CH0114_home.skel?binary'),
    'CH0114_home.atlas': () => import('@atlas/CH0114_home.atlas?raw'),
    'CH0114_home2.png': () => import('@png/CH0114_home2.png?binary'),
    'CH0114_home.png': () => import('@png/CH0114_home.png?binary'),

    'Hiyori_home.skel': () => import('@skel/Hiyori_home.skel?binary'),
    'Hiyori_home.atlas': () => import('@atlas/Hiyori_home.atlas?raw'),
    'Hiyori_home2.png': () => import('@png/Hiyori_home2.png?binary'),
    'Hiyori_home.png': () => import('@png/Hiyori_home.png?binary'),

    'Misaki_home.skel': () => import('@skel/Misaki_home.skel?binary'),
    'Misaki_home.atlas': () => import('@atlas/Misaki_home.atlas?raw'),
    'Misaki_home2.png': () => import('@png/Misaki_home2.png?binary'),
    'Misaki_home.png': () => import('@png/Misaki_home.png?binary'),

    'Atsuko_home.skel': () => import('@skel/Atsuko_home.skel?binary'),
    'Atsuko_home.atlas': () => import('@atlas/Atsuko_home.atlas?raw'),
    'Atsuko_home2.png': () => import('@png/Atsuko_home2.png?binary'),
    'Atsuko_home.png': () => import('@png/Atsuko_home.png?binary'),

    'CH0176_home.skel': () => import('@skel/CH0176_home.skel?binary'),
    'CH0176_home.atlas': () => import('@atlas/CH0176_home.atlas?raw'),
    'CH0176_home2.png': () => import('@png/CH0176_home2.png?binary'),
    'CH0176_home.png': () => import('@png/CH0176_home.png?binary'),

    'CH0092_home.skel': () => import('@skel/CH0092_home.skel?binary'),
    'CH0092_home.atlas': () => import('@atlas/CH0092_home.atlas?raw'),
    'CH0092_home3.png': () => import('@png/CH0092_home3.png?binary'),
    'CH0092_home2.png': () => import('@png/CH0092_home2.png?binary'),
    'CH0092_home.png': () => import('@png/CH0092_home.png?binary'),

    'CH0175_home.skel': () => import('@skel/CH0175_home.skel?binary'),
    'CH0175_home.atlas': () => import('@atlas/CH0175_home.atlas?raw'),
    'CH0175_home2.png': () => import('@png/CH0175_home2.png?binary'),
    'CH0175_home.png': () => import('@png/CH0175_home.png?binary'),

    'Hoshino_swimsuit_home.skel': () => import('@skel/Hoshino_swimsuit_home.skel?binary'),
    'Hoshino_swimsuit_home.atlas': () => import('@atlas/Hoshino_swimsuit_home.atlas?raw'),
    'Hoshino_swimsuit_home3.png': () => import('@png/Hoshino_swimsuit_home3.png?binary'),
    'Hoshino_swimsuit_home2.png': () => import('@png/Hoshino_swimsuit_home2.png?binary'),
    'Hoshino_swimsuit_home.png': () => import('@png/Hoshino_swimsuit_home.png?binary'),

    'CH0180_home.skel': () => import('@skel/CH0180_home.skel?binary'),
    'CH0180_home.atlas': () => import('@atlas/CH0180_home.atlas?raw'),
    'CH0180_home2.png': () => import('@png/CH0180_home2.png?binary'),
    'CH0180_home.png': () => import('@png/CH0180_home.png?binary'),

    'CH0178_home.skel': () => import('@skel/CH0178_home.skel?binary'),
    'CH0178_home.atlas': () => import('@atlas/CH0178_home.atlas?raw'),
    'CH0178_home3.png': () => import('@png/CH0178_home3.png?binary'),
    'CH0178_home2.png': () => import('@png/CH0178_home2.png?binary'),
    'CH0178_home.png': () => import('@png/CH0178_home.png?binary'),

    'CH0179_home.skel': () => import('@skel/CH0179_home.skel?binary'),
    'CH0179_home.atlas': () => import('@atlas/CH0179_home.atlas?raw'),
    'CH0179_home3.png': () => import('@png/CH0179_home3.png?binary'),
    'CH0179_home2.png': () => import('@png/CH0179_home2.png?binary'),
    'CH0179_home.png': () => import('@png/CH0179_home.png?binary'),

    'Saori_home.skel': () => import('@skel/Saori_home.skel?binary'),
    'Saori_home.atlas': () => import('@atlas/Saori_home.atlas?raw'),
    'Saori_home2.png': () => import('@png/Saori_home2.png?binary'),
    'Saori_home.png': () => import('@png/Saori_home.png?binary'),


    'Moe_home.skel': () => import('@skel/Moe_home.skel?binary'),
    'Moe_home.atlas': () => import('@atlas/Moe_home.atlas?raw'),
    'Moe_home4.png': () => import('@png/Moe_home4.png?binary'),
    'Moe_home3.png': () => import('@png/Moe_home3.png?binary'),
    'Moe_home2.png': () => import('@png/Moe_home2.png?binary'),
    'Moe_home.png': () => import('@png/Moe_home.png?binary'),

    'CH0137_home.skel': () => import('@skel/CH0137_home.skel?binary'),
    'CH0137_home.atlas': () => import('@atlas/CH0137_home.atlas?raw'),
    'CH0137_home2.png': () => import('@png/CH0137_home2.png?binary'),
    'CH0137_home.png': () => import('@png/CH0137_home.png?binary'),

    'CH0181_home.skel': () => import('@skel/CH0181_home.skel?binary'),
    'CH0181_home.atlas': () => import('@atlas/CH0181_home.atlas?raw'),
    'CH0181_home2.png': () => import('@png/CH0181_home2.png?binary'),
    'CH0181_home.png': () => import('@png/CH0181_home.png?binary'),

    'CH0095_home.skel': () => import('@skel/CH0095_home.skel?binary'),
    'CH0095_home.atlas': () => import('@atlas/CH0095_home.atlas?raw'),
    'CH0095_home2.png': () => import('@png/CH0095_home2.png?binary'),
    'CH0095_home.png': () => import('@png/CH0095_home.png?binary'),

    'CH0182_home.skel': () => import('@skel/CH0182_home.skel?binary'),
    'CH0182_home.atlas': () => import('@atlas/CH0182_home.atlas?raw'),
    'CH0182_home2.png': () => import('@png/CH0182_home2.png?binary'),
    'CH0182_home.png': () => import('@png/CH0182_home.png?binary'),

    'CH0099_home.skel': () => import('@skel/CH0099_home.skel?binary'),
    'CH0099_home.atlas': () => import('@atlas/CH0099_home.atlas?raw'),
    'CH0099_home2.png': () => import('@png/CH0099_home2.png?binary'),
    'CH0099_home.png': () => import('@png/CH0099_home.png?binary'),

    'CH0190_home.skel': () => import('@skel/CH0190_home.skel?binary'),
    'CH0190_home.atlas': () => import('@atlas/CH0190_home.atlas?raw'),
    'CH0190_home2.png': () => import('@png/CH0190_home2.png?binary'),
    'CH0190_home.png': () => import('@png/CH0190_home.png?binary'),

    'CH0186_home.skel': () => import('@skel/CH0186_home.skel?binary'),
    'CH0186_home.atlas': () => import('@atlas/CH0186_home.atlas?raw'),
    'CH0186_home2.png': () => import('@png/CH0186_home2.png?binary'),
    'CH0186_home.png': () => import('@png/CH0186_home.png?binary'),

    'CH0184_home.skel': () => import('@skel/CH0184_home.skel?binary'),
    'CH0184_00.skel': () => import('@skel/CH0184_00.skel?binary'),
    'CH0184_home.atlas': () => import('@atlas/CH0184_home.atlas?raw'),
    'CH0184_00.atlas': () => import('@atlas/CH0184_00.atlas?raw'),
    'CH0184_home3.png': () => import('@png/CH0184_home3.png?binary'),
    'CH0184_home2.png': () => import('@png/CH0184_home2.png?binary'),
    'CH0184_home.png': () => import('@png/CH0184_home.png?binary'),

    'CH0159_home.skel': () => import('@skel/CH0159_home.skel?binary'),
    'CH0159_home.atlas': () => import('@atlas/CH0159_home.atlas?raw'),
    'CH0159_home3.png': () => import('@png/CH0159_home3.png?binary'),
    'CH0159_home2.png': () => import('@png/CH0159_home2.png?binary'),
    'CH0159_home.png': () => import('@png/CH0159_home.png?binary'),

    'Shigure_home.skel': () => import('@skel/Shigure_home.skel?binary'),
    'Shigure_01.skel': () => import('@skel/Shigure_01.skel?binary'),
    'Shigure_00.skel': () => import('@skel/Shigure_00.skel?binary'),
    'Shigure_home.atlas': () => import('@atlas/Shigure_home.atlas?raw'),
    'Shigure_01.atlas': () => import('@atlas/Shigure_01.atlas?raw'),
    'Shigure_00.atlas': () => import('@atlas/Shigure_00.atlas?raw'),
    'Shigure_home2.png': () => import('@png/Shigure_home2.png?binary'),
    'Shigure_home.png': () => import('@png/Shigure_home.png?binary'),

    'CH0195_home.skel': () => import('@skel/CH0195_home.skel?binary'),
    'CH0195_home.atlas': () => import('@atlas/CH0195_home.atlas?raw'),
    'CH0195_home2.png': () => import('@png/CH0195_home2.png?binary'),
    'CH0195_home.png': () => import('@png/CH0195_home.png?binary'),

    'CH0194_home.skel': () => import('@skel/CH0194_home.skel?binary'),
    'CH0194_home.atlas': () => import('@atlas/CH0194_home.atlas?raw'),
    'CH0194_home2.png': () => import('@png/CH0194_home2.png?binary'),
    'CH0194_home.png': () => import('@png/CH0194_home.png?binary'),

    'CH0177_home.skel': () => import('@skel/CH0177_home.skel?binary'),
    'CH0177_home.atlas': () => import('@atlas/CH0177_home.atlas?raw'),
    'CH0177_home2.png': () => import('@png/CH0177_home2.png?binary'),
    'CH0177_home.png': () => import('@png/CH0177_home.png?binary'),

    'CH0191_home.skel': () => import('@skel/CH0191_home.skel?binary'),
    'CH0191_home.atlas': () => import('@atlas/CH0191_home.atlas?raw'),
    'CH0191_home2.png': () => import('@png/CH0191_home2.png?binary'),
    'CH0191_home.png': () => import('@png/CH0191_home.png?binary'),

    'CH0192_home.skel': () => import('@skel/CH0192_home.skel?binary'),
    'CH0192_home.atlas': () => import('@atlas/CH0192_home.atlas?raw'),
    'CH0192_home2.png': () => import('@png/CH0192_home2.png?binary'),
    'CH0192_home.png': () => import('@png/CH0192_home.png?binary'),

    'CH0152_home.skel': () => import('@skel/CH0152_home.skel?binary'),
    'CH0152_home.atlas': () => import('@atlas/CH0152_home.atlas?raw'),
    'CH0152_home4.png': () => import('@png/CH0152_home4.png?binary'),
    'CH0152_home3.png': () => import('@png/CH0152_home3.png?binary'),
    'CH0152_home2.png': () => import('@png/CH0152_home2.png?binary'),
    'CH0152_home.png': () => import('@png/CH0152_home.png?binary'),

    'CH0069_home.skel': () => import('@skel/CH0069_home.skel?binary'),
    'CH0069_home.atlas': () => import('@atlas/CH0069_home.atlas?raw'),
    'CH0069_home4.png': () => import('@png/CH0069_home4.png?binary'),
    'CH0069_home3.png': () => import('@png/CH0069_home3.png?binary'),
    'CH0069_home2.png': () => import('@png/CH0069_home2.png?binary'),
    'CH0069_home.png': () => import('@png/CH0069_home.png?binary'),

    'CH0170_home.skel': () => import('@skel/CH0170_home.skel?binary'),
    'CH0170_home.atlas': () => import('@atlas/CH0170_home.atlas?raw'),
    'CH0170_home2.png': () => import('@png/CH0170_home2.png?binary'),
    'CH0170_home.png': () => import('@png/CH0170_home.png?binary'),

    'CH0088_home.skel': () => import('@skel/CH0088_home.skel?binary'),
    'CH0088_home.atlas': () => import('@atlas/CH0088_home.atlas?raw'),
    'CH0088_home3.png': () => import('@png/CH0088_home3.png?binary'),
    'CH0088_home2.png': () => import('@png/CH0088_home2.png?binary'),
    'CH0088_home.png': () => import('@png/CH0088_home.png?binary'),

    'Sakurako_home.skel': () => import('@skel/Sakurako_home.skel?binary'),
    'Sakurako_home.atlas': () => import('@atlas/Sakurako_home.atlas?raw'),
    'Sakurako_home3.png': () => import('@png/Sakurako_home3.png?binary'),
    'Sakurako_home2.png': () => import('@png/Sakurako_home2.png?binary'),
    'Sakurako_home.png': () => import('@png/Sakurako_home.png?binary'),

    'Nagisa_home.skel': () => import('@skel/Nagisa_home.skel?binary'),
    'Nagisa_home.atlas': () => import('@atlas/Nagisa_home.atlas?raw'),
    'Nagisa_home2.png': () => import('@png/Nagisa_home2.png?binary'),
    'Nagisa_home.png': () => import('@png/Nagisa_home.png?binary'),

    'CH0187_home.skel': () => import('@skel/CH0187_home.skel?binary'),
    'CH0187_home.atlas': () => import('@atlas/CH0187_home.atlas?raw'),
    'CH0187_home3.png': () => import('@png/CH0187_home3.png?binary'),
    'CH0187_home2.png': () => import('@png/CH0187_home2.png?binary'),
    'CH0187_home.png': () => import('@png/CH0187_home.png?binary'),

    'CH0198_home.skel': () => import('@skel/CH0198_home.skel?binary'),
    'CH0198_home.atlas': () => import('@atlas/CH0198_home.atlas?raw'),
    'CH0198_home3.png': () => import('@png/CH0198_home3.png?binary'),
    'CH0198_home2.png': () => import('@png/CH0198_home2.png?binary'),
    'CH0198_home.png': () => import('@png/CH0198_home.png?binary'),

    'CH0087_home.skel': () => import('@skel/CH0087_home.skel?binary'),
    'CH0087_home.atlas': () => import('@atlas/CH0087_home.atlas?raw'),
    'CH0087_home3.png': () => import('@png/CH0087_home3.png?binary'),
    'CH0087_home2.png': () => import('@png/CH0087_home2.png?binary'),
    'CH0087_home.png': () => import('@png/CH0087_home.png?binary'),

    'CH0086_home.skel': () => import('@skel/CH0086_home.skel?binary'),
    'CH0086_home.atlas': () => import('@atlas/CH0086_home.atlas?raw'),
    'CH0086_home3.png': () => import('@png/CH0086_home3.png?binary'),
    'CH0086_home2.png': () => import('@png/CH0086_home2.png?binary'),
    'CH0086_home.png': () => import('@png/CH0086_home.png?binary'),

    'CH0107_home.skel': () => import('@skel/CH0107_home.skel?binary'),
    'CH0107_home.atlas': () => import('@atlas/CH0107_home.atlas?raw'),
    'CH0107_home3.png': () => import('@png/CH0107_home3.png?binary'),
    'CH0107_home2.png': () => import('@png/CH0107_home2.png?binary'),
    'CH0107_home.png': () => import('@png/CH0107_home.png?binary'),

    'CH0200_home.skel': () => import('@skel/CH0200_home.skel?binary'),
    'CH0200_home.atlas': () => import('@atlas/CH0200_home.atlas?raw'),
    'CH0200_home2.png': () => import('@png/CH0200_home2.png?binary'),
    'CH0200_home.png': () => import('@png/CH0200_home.png?binary'),

    'CH0211_home.skel': () => import('@skel/CH0211_home.skel?binary'),
    'CH0211_home.atlas': () => import('@atlas/CH0211_home.atlas?raw'),
    'CH0211_home2.png': () => import('@png/CH0211_home2.png?binary'),
    'CH0211_home.png': () => import('@png/CH0211_home.png?binary'),

    'CH0203_home.skel': () => import('@skel/CH0203_home.skel?binary'),
    'CH0203_home.atlas': () => import('@atlas/CH0203_home.atlas?raw'),
    'CH0203_home3.png': () => import('@png/CH0203_home3.png?binary'),
    'CH0203_home2.png': () => import('@png/CH0203_home2.png?binary'),
    'CH0203_home.png': () => import('@png/CH0203_home.png?binary'),

    'CH0167_home.skel': () => import('@skel/CH0167_home.skel?binary'),
    'CH0167_home.atlas': () => import('@atlas/CH0167_home.atlas?raw'),
    'CH0167_home3.png': () => import('@png/CH0167_home3.png?binary'),
    'CH0167_home2.png': () => import('@png/CH0167_home2.png?binary'),
    'CH0167_home.png': () => import('@png/CH0167_home.png?binary'),

    'CH0138_home.skel': () => import('@skel/CH0138_home.skel?binary'),
    'CH0138_home.atlas': () => import('@atlas/CH0138_home.atlas?raw'),
    'CH0138_home3.png': () => import('@png/CH0138_home3.png?binary'),
    'CH0138_home2.png': () => import('@png/CH0138_home2.png?binary'),
    'CH0138_home.png': () => import('@png/CH0138_home.png?binary'),

    'CH0135_home.skel': () => import('@skel/CH0135_home.skel?binary'),
    'CH0135_home.atlas': () => import('@atlas/CH0135_home.atlas?raw'),
    'CH0135_home2.png': () => import('@png/CH0135_home2.png?binary'),
    'CH0135_home.png': () => import('@png/CH0135_home.png?binary'),

    'CH0214_home.skel': () => import('@skel/CH0214_home.skel?binary'),
    'CH0214_home.atlas': () => import('@atlas/CH0214_home.atlas?raw'),
    'CH0214_home3.png': () => import('@png/CH0214_home3.png?binary'),
    'CH0214_home2.png': () => import('@png/CH0214_home2.png?binary'),
    'CH0214_home.png': () => import('@png/CH0214_home.png?binary'),

    'CH0215_home.skel': () => import('@skel/CH0215_home.skel?binary'),
    'CH0215_home.atlas': () => import('@atlas/CH0215_home.atlas?raw'),
    'CH0215_home3.png': () => import('@png/CH0215_home3.png?binary'),
    'CH0215_home2.png': () => import('@png/CH0215_home2.png?binary'),
    'CH0215_home.png': () => import('@png/CH0215_home.png?binary'),

    'CH0218_home.skel': () => import('@skel/CH0218_home.skel?binary'),
    'CH0218_home.atlas': () => import('@atlas/CH0218_home.atlas?raw'),
    'CH0218_home3.png': () => import('@png/CH0218_home3.png?binary'),
    'CH0218_home2.png': () => import('@png/CH0218_home2.png?binary'),
    'CH0218_home.png': () => import('@png/CH0218_home.png?binary'),

    'CH0217_home.skel': () => import('@skel/CH0217_home.skel?binary'),
    'CH0217_home.atlas': () => import('@atlas/CH0217_home.atlas?raw'),
    'CH0217_home3.png': () => import('@png/CH0217_home3.png?binary'),
    'CH0217_home2.png': () => import('@png/CH0217_home2.png?binary'),
    'CH0217_home.png': () => import('@png/CH0217_home.png?binary'),

    'CH0188_home.skel': () => import('@skel/CH0188_home.skel?binary'),
    'CH0188_home.atlas': () => import('@atlas/CH0188_home.atlas?raw'),
    'CH0188_home4.png': () => import('@png/CH0188_home4.png?binary'),
    'CH0188_home3.png': () => import('@png/CH0188_home3.png?binary'),
    'CH0188_home2.png': () => import('@png/CH0188_home2.png?binary'),
    'CH0188_home.png': () => import('@png/CH0188_home.png?binary'),

    'CH0210_home.skel': () => import('@skel/CH0210_home.skel?binary'),
    'CH0210_home.atlas': () => import('@atlas/CH0210_home.atlas?raw'),
    'CH0210_home3.png': () => import('@png/CH0210_home3.png?binary'),
    'CH0210_home2.png': () => import('@png/CH0210_home2.png?binary'),
    'CH0210_home.png': () => import('@png/CH0210_home.png?binary'),

    'CH0205_home.skel': () => import('@skel/CH0205_home.skel?binary'),
    'CH0205_home.atlas': () => import('@atlas/CH0205_home.atlas?raw'),
    'CH0205_home3.png': () => import('@png/CH0205_home3.png?binary'),
    'CH0205_home2.png': () => import('@png/CH0205_home2.png?binary'),
    'CH0205_home.png': () => import('@png/CH0205_home.png?binary'),

    'CH0204_home.skel': () => import('@skel/CH0204_home.skel?binary'),
    'CH0204_home.atlas': () => import('@atlas/CH0204_home.atlas?raw'),
    'CH0204_home3.png': () => import('@png/CH0204_home3.png?binary'),
    'CH0204_home2.png': () => import('@png/CH0204_home2.png?binary'),
    'CH0204_home.png': () => import('@png/CH0204_home.png?binary'),

    'CH0209_home.skel': () => import('@skel/CH0209_home.skel?binary'),
    'CH0209_home.atlas': () => import('@atlas/CH0209_home.atlas?raw'),
    'CH0209_home3.png': () => import('@png/CH0209_home3.png?binary'),
    'CH0209_home2.png': () => import('@png/CH0209_home2.png?binary'),
    'CH0209_home.png': () => import('@png/CH0209_home.png?binary'),

    'CH0183_home.skel': () => import('@skel/CH0183_home.skel?binary'),
    'CH0183_home.atlas': () => import('@atlas/CH0183_home.atlas?raw'),
    'CH0183_home2.png': () => import('@png/CH0183_home2.png?binary'),
    'CH0183_home.png': () => import('@png/CH0183_home.png?binary'),

    'CH0124_home.skel': () => import('@skel/CH0124_home.skel?binary'),
    'CH0124_home.atlas': () => import('@atlas/CH0124_home.atlas?raw'),
    'CH0124_home3.png': () => import('@png/CH0124_home3.png?binary'),
    'CH0124_home2.png': () => import('@png/CH0124_home2.png?binary'),
    'CH0124_home.png': () => import('@png/CH0124_home.png?binary'),


    'CH0185_home.skel': () => import('@skel/CH0185_home.skel?binary'),
    'CH0185_home.atlas': () => import('@atlas/CH0185_home.atlas?raw'),
    'CH0185_home2.png': () => import('@png/CH0185_home2.png?binary'),
    'CH0185_home.png': () => import('@png/CH0185_home.png?binary'),

    'CH0193_home.skel': () => import('@skel/CH0193_home.skel?binary'),
    'CH0193_home.atlas': () => import('@atlas/CH0193_home.atlas?raw'),
    'CH0193_home2.png': () => import('@png/CH0193_home2.png?binary'),
    'CH0193_home.png': () => import('@png/CH0193_home.png?binary'),

    'CH0071_home.skel': () => import('@skel/CH0071_home.skel?binary'),
    'CH0071_home.atlas': () => import('@atlas/CH0071_home.atlas?raw'),
    'CH0071_home3.png': () => import('@png/CH0071_home3.png?binary'),
    'CH0071_home2.png': () => import('@png/CH0071_home2.png?binary'),
    'CH0071_home.png': () => import('@png/CH0071_home.png?binary'),

    'CH0089_home.skel': () => import('@skel/CH0089_home.skel?binary'),
    'CH0089_home.atlas': () => import('@atlas/CH0089_home.atlas?raw'),
    'CH0089_home3.png': () => import('@png/CH0089_home3.png?binary'),
    'CH0089_home2.png': () => import('@png/CH0089_home2.png?binary'),
    'CH0089_home.png': () => import('@png/CH0089_home.png?binary'),

    'CH0123_home.skel': () => import('@skel/CH0123_home.skel?binary'),
    'CH0123_home.atlas': () => import('@atlas/CH0123_home.atlas?raw'),
    'CH0123_home3.png': () => import('@png/CH0123_home3.png?binary'),
    'CH0123_home2.png': () => import('@png/CH0123_home2.png?binary'),
    'CH0123_home.png': () => import('@png/CH0123_home.png?binary'),

    'CH9998_home.skel': () => import('@skel/CH9998_home.skel?binary'),
    'CH9998_home.atlas': () => import('@atlas/CH9998_home.atlas?raw'),
    'CH9998_home2.png': () => import('@png/CH9998_home2.png?binary'),
    'CH9998_home.png': () => import('@png/CH9998_home.png?binary'),

    'CH9996_home.skel': () => import('@skel/CH9996_home.skel?binary'),

    'CH9997_home.skel': () => import('@skel/CH9997_home.skel?binary'),
    'CH9997_home.atlas': () => import('@atlas/CH9997_home.atlas?raw'),
    'CH9997_home3.png': () => import('@png/CH9997_home3.png?binary'),
    'CH9997_home2.png': () => import('@png/CH9997_home2.png?binary'),
    'CH9997_home.png': () => import('@png/CH9997_home.png?binary'),

    'CH0161_home.skel': () => import('@skel/CH0161_home.skel?binary'),
    'CH0161_home.atlas': () => import('@atlas/CH0161_home.atlas?raw'),
    'CH0161_home4.png': () => import('@png/CH0161_home4.png?binary'),
    'CH0161_home3.png': () => import('@png/CH0161_home3.png?binary'),
    'CH0161_home2.png': () => import('@png/CH0161_home2.png?binary'),
    'CH0161_home.png': () => import('@png/CH0161_home.png?binary'),

    'CH0225_home.skel': () => import('@skel/CH0225_home.skel?binary'),
    'CH0225_home.atlas': () => import('@atlas/CH0225_home.atlas?raw'),
    'CH0225_home3.png': () => import('@png/CH0225_home3.png?binary'),
    'CH0225_home2.png': () => import('@png/CH0225_home2.png?binary'),
    'CH0225_home.png': () => import('@png/CH0225_home.png?binary'),

    'CH0224_home.skel': () => import('@skel/CH0224_home.skel?binary'),
    'CH0224_home.atlas': () => import('@atlas/CH0224_home.atlas?raw'),
    'CH0224_home3.png': () => import('@png/CH0224_home3.png?binary'),
    'CH0224_home2.png': () => import('@png/CH0224_home2.png?binary'),
    'CH0224_home.png': () => import('@png/CH0224_home.png?binary'),


    'CH0233_home.skel': () => import('@skel/CH0233_home.skel?binary'),
    'CH0233_home.atlas': () => import('@atlas/CH0233_home.atlas?raw'),
    'CH0233_home3.png': () => import('@png/CH0233_home3.png?binary'),
    'CH0233_home2.png': () => import('@png/CH0233_home2.png?binary'),
    'CH0233_home.png': () => import('@png/CH0233_home.png?binary'),

    'CH0232_home.skel': () => import('@skel/CH0232_home.skel?binary'),
    'CH0232_home.atlas': () => import('@atlas/CH0232_home.atlas?raw'),
    'CH0232_home3.png': () => import('@png/CH0232_home3.png?binary'),
    'CH0232_home2.png': () => import('@png/CH0232_home2.png?binary'),
    'CH0232_home.png': () => import('@png/CH0232_home.png?binary'),

    'CH0231_home.skel': () => import('@skel/CH0231_home.skel?binary'),
    'CH0231_home.atlas': () => import('@atlas/CH0231_home.atlas?raw'),
    'CH0231_home2.png': () => import('@png/CH0231_home2.png?binary'),
    'CH0231_home.png': () => import('@png/CH0231_home.png?binary'),

    'Ibuki_home.skel': () => import('@skel/Ibuki_home.skel?binary'),
    'Ibuki_home.atlas': () => import('@atlas/Ibuki_home.atlas?raw'),
    'Ibuki_home3.png': () => import('@png/Ibuki_home3.png?binary'),
    'Ibuki_home2.png': () => import('@png/Ibuki_home2.png?binary'),
    'Ibuki_home.png': () => import('@png/Ibuki_home.png?binary'),

    'CH0079_home.skel': () => import('@skel/CH0079_home.skel?binary'),
    'CH0079_home.atlas': () => import('@atlas/CH0079_home.atlas?raw'),
    'CH0079_home3.png': () => import('@png/CH0079_home3.png?binary'),
    'CH0079_home2.png': () => import('@png/CH0079_home2.png?binary'),
    'CH0079_home.png': () => import('@png/CH0079_home.png?binary'),

    'CH0230_home.skel': () => import('@skel/CH0230_home.skel?binary'),
    'CH0230_home.atlas': () => import('@atlas/CH0230_home.atlas?raw'),
    'CH0230_home4.png': () => import('@png/CH0230_home4.png?binary'),
    'CH0230_home3.png': () => import('@png/CH0230_home3.png?binary'),
    'CH0230_home2.png': () => import('@png/CH0230_home2.png?binary'),
    'CH0230_home.png': () => import('@png/CH0230_home.png?binary'),

    'CH0240_home.skel': () => import('@skel/CH0240_home.skel?binary'),
    'CH0240_home.atlas': () => import('@atlas/CH0240_home.atlas?raw'),
    'CH0240_home3.png': () => import('@png/CH0240_home3.png?binary'),
    'CH0240_home2.png': () => import('@png/CH0240_home2.png?binary'),
    'CH0240_home.png': () => import('@png/CH0240_home.png?binary'),

    'CH0239_home.skel': () => import('@skel/CH0239_home.skel?binary'),
    'CH0239_home.atlas': () => import('@atlas/CH0239_home.atlas?raw'),
    'CH0239_home4.png': () => import('@png/CH0239_home4.png?binary'),
    'CH0239_home3.png': () => import('@png/CH0239_home3.png?binary'),
    'CH0239_home2.png': () => import('@png/CH0239_home2.png?binary'),
    'CH0239_home.png': () => import('@png/CH0239_home.png?binary'),

    'CH0196_home.skel': () => import('@skel/CH0196_home.skel?binary'),
    'CH0196_home.atlas': () => import('@atlas/CH0196_home.atlas?raw'),
    'CH0196_home3.png': () => import('@png/CH0196_home3.png?binary'),
    'CH0196_home2.png': () => import('@png/CH0196_home2.png?binary'),
    'CH0196_home.png': () => import('@png/CH0196_home.png?binary'),

    'CH0255_home.skel': () => import('@skel/CH0255_home.skel?binary'),
    'CH0255_home.atlas': () => import('@atlas/CH0255_home.atlas?raw'),
    'CH0255_home3.png': () => import('@png/CH0255_home3.png?binary'),
    'CH0255_home2.png': () => import('@png/CH0255_home2.png?binary'),
    'CH0255_home.png': () => import('@png/CH0255_home.png?binary'),

    'CH0110_home.skel': () => import('@skel/CH0110_home.skel?binary'),
    'CH0110_home.atlas': () => import('@atlas/CH0110_home.atlas?raw'),
    'CH0110_home4.png': () => import('@png/CH0110_home4.png?binary'),
    'CH0110_home3.png': () => import('@png/CH0110_home3.png?binary'),
    'CH0110_home2.png': () => import('@png/CH0110_home2.png?binary'),
    'CH0110_home.png': () => import('@png/CH0110_home.png?binary'),

    'CH0251_home.skel': () => import('@skel/CH0251_home.skel?binary'),
    'CH0251_home.atlas': () => import('@atlas/CH0251_home.atlas?raw'),
    'CH0251_home2.png': () => import('@png/CH0251_home2.png?binary'),
    'CH0251_home.png': () => import('@png/CH0251_home.png?binary'),

    'CH0250_home.skel': () => import('@skel/CH0250_home.skel?binary'),
    'CH0250_home.atlas': () => import('@atlas/CH0250_home.atlas?raw'),
    'CH0250_home3.png': () => import('@png/CH0250_home3.png?binary'),
    'CH0250_home2.png': () => import('@png/CH0250_home2.png?binary'),
    'CH0250_home.png': () => import('@png/CH0250_home.png?binary'),

    'CH0220_home.skel': () => import('@skel/CH0220_home.skel?binary'),
    'CH0220_home.atlas': () => import('@atlas/CH0220_home.atlas?raw'),
    'CH0220_home3.png': () => import('@png/CH0220_home3.png?binary'),
    'CH0220_home2.png': () => import('@png/CH0220_home2.png?binary'),
    'CH0220_home.png': () => import('@png/CH0220_home.png?binary'),

    'Kirara_home.skel': () => import('@skel/Kirara_home.skel?binary'),
    'Kirara_home.atlas': () => import('@atlas/Kirara_home.atlas?raw'),
    'Kirara_home2.png': () => import('@png/Kirara_home2.png?binary'),
    'Kirara_home.png': () => import('@png/Kirara_home.png?binary'),

    'CH0202_home.skel': () => import('@skel/CH0202_home.skel?binary'),
    'CH0202_home.atlas': () => import('@atlas/CH0202_home.atlas?raw'),
    'CH0202_home3.png': () => import('@png/CH0202_home3.png?binary'),
    'CH0202_home2.png': () => import('@png/CH0202_home2.png?binary'),
    'CH0202_home.png': () => import('@png/CH0202_home.png?binary'),

    'CH0201_home.skel': () => import('@skel/CH0201_home.skel?binary'),
    'CH0201_home.atlas': () => import('@atlas/CH0201_home.atlas?raw'),
    'CH0201_home3.png': () => import('@png/CH0201_home3.png?binary'),
    'CH0201_home2.png': () => import('@png/CH0201_home2.png?binary'),
    'CH0201_home.png': () => import('@png/CH0201_home.png?binary'),

    'CH0189_home.skel': () => import('@skel/CH0189_home.skel?binary'),
    'CH0189_home.atlas': () => import('@atlas/CH0189_home.atlas?raw'),
    'CH0189_home3.png': () => import('@png/CH0189_home3.png?binary'),
    'CH0189_home2.png': () => import('@png/CH0189_home2.png?binary'),
    'CH0189_home.png': () => import('@png/CH0189_home.png?binary'),

    'CH0261_home.skel': () => import('@skel/CH0261_home.skel?binary'),
    'CH0261_home.atlas': () => import('@atlas/CH0261_home.atlas?raw'),
    'CH0261_home3.png': () => import('@png/CH0261_home3.png?binary'),
    'CH0261_home2.png': () => import('@png/CH0261_home2.png?binary'),
    'CH0261_home.png': () => import('@png/CH0261_home.png?binary'),

    'CH0260_home.skel': () => import('@skel/CH0260_home.skel?binary'),
    'CH0260_home.atlas': () => import('@atlas/CH0260_home.atlas?raw'),
    'CH0260_home3.png': () => import('@png/CH0260_home3.png?binary'),
    'CH0260_home2.png': () => import('@png/CH0260_home2.png?binary'),
    'CH0260_home.png': () => import('@png/CH0260_home.png?binary'),

    'CH0262_home.skel': () => import('@skel/CH0262_home.skel?binary'),
    'CH0262_home.atlas': () => import('@atlas/CH0262_home.atlas?raw'),
    'CH0262_home2.png': () => import('@png/CH0262_home2.png?binary'),
    'CH0262_home.png': () => import('@png/CH0262_home.png?binary'),

    'CH0216_home.skel': () => import('@skel/CH0216_home.skel?binary'),
    'CH0216_home.atlas': () => import('@atlas/CH0216_home.atlas?raw'),
    'CH0216_home3.png': () => import('@png/CH0216_home3.png?binary'),
    'CH0216_home2.png': () => import('@png/CH0216_home2.png?binary'),
    'CH0216_home.png': () => import('@png/CH0216_home.png?binary'),

    'CH0267_home.skel': () => import('@skel/CH0267_home.skel?binary'),
    'CH0267_home.atlas': () => import('@atlas/CH0267_home.atlas?raw'),
    'CH0267_home3.png': () => import('@png/CH0267_home3.png?binary'),
    'CH0267_home2.png': () => import('@png/CH0267_home2.png?binary'),
    'CH0267_home.png': () => import('@png/CH0267_home.png?binary'),

    'CH0258_home.skel': () => import('@skel/CH0258_home.skel?binary'),
    'CH0258_home.atlas': () => import('@atlas/CH0258_home.atlas?raw'),
    'CH0258_home3.png': () => import('@png/CH0258_home3.png?binary'),
    'CH0258_home2.png': () => import('@png/CH0258_home2.png?binary'),
    'CH0258_home.png': () => import('@png/CH0258_home.png?binary'),

    'CH0263_home.skel': () => import('@skel/CH0263_home.skel?binary'),
    'CH0263_home.atlas': () => import('@atlas/CH0263_home.atlas?raw'),
    'CH0263_home4.png': () => import('@png/CH0263_home4.png?binary'),
    'CH0263_home3.png': () => import('@png/CH0263_home3.png?binary'),
    'CH0263_home2.png': () => import('@png/CH0263_home2.png?binary'),
    'CH0263_home.png': () => import('@png/CH0263_home.png?binary'),

    'CH0269_home.skel': () => import('@skel/CH0269_home.skel?binary'),
    'CH0269_home.atlas': () => import('@atlas/CH0269_home.atlas?raw'),
    'CH0269_home3.png': () => import('@png/CH0269_home3.png?binary'),
    'CH0269_home2.png': () => import('@png/CH0269_home2.png?binary'),
    'CH0269_home.png': () => import('@png/CH0269_home.png?binary'),

    'CH0266_home.skel': () => import('@skel/CH0266_home.skel?binary'),
    'CH0266_home.atlas': () => import('@atlas/CH0266_home.atlas?raw'),
    'CH0266_home3.png': () => import('@png/CH0266_home3.png?binary'),
    'CH0266_home2.png': () => import('@png/CH0266_home2.png?binary'),
    'CH0266_home.png': () => import('@png/CH0266_home.png?binary'),

    'CH0270_home.skel': () => import('@skel/CH0270_home.skel?binary'),
    'CH0270_home.atlas': () => import('@atlas/CH0270_home.atlas?raw'),
    'CH0270_home2.png': () => import('@png/CH0270_home2.png?binary'),
    'CH0270_home.png': () => import('@png/CH0270_home.png?binary'),

    'CH0271_home.skel': () => import('@skel/CH0271_home.skel?binary'),
    'CH0271_home.atlas': () => import('@atlas/CH0271_home.atlas?raw'),
    'CH0271_home2.png': () => import('@png/CH0271_home2.png?binary'),
    'CH0271_home.png': () => import('@png/CH0271_home.png?binary'),

    'CH0139_home.skel': () => import('@skel/CH0139_home.skel?binary'),
    'CH0139_home.atlas': () => import('@atlas/CH0139_home.atlas?raw'),
    'CH0139_home2.png': () => import('@png/CH0139_home2.png?binary'),
    'CH0139_home.png': () => import('@png/CH0139_home.png?binary'),


    'CH0273_home.skel': () => import('@skel/CH0273_home.skel?binary'),
    'CH0273_home.atlas': () => import('@atlas/CH0273_home.atlas?raw'),
    'CH0273_home_2.png': () => import('@png/CH0273_home_2.png?binary'),
    'CH0273_home.png': () => import('@png/CH0273_home.png?binary'),

    'CH0274_home.skel': () => import('@skel/CH0274_home.skel?binary'),
    'CH0274_home.atlas': () => import('@atlas/CH0274_home.atlas?raw'),
    'CH0274_home3.png': () => import('@png/CH0274_home3.png?binary'),
    'CH0274_home2.png': () => import('@png/CH0274_home2.png?binary'),
    'CH0274_home.png': () => import('@png/CH0274_home.png?binary'),

    'CH0275_home.skel': () => import('@skel/CH0275_home.skel?binary'),
    'CH0275_home.atlas': () => import('@atlas/CH0275_home.atlas?raw'),
    'CH0275_home_2.png': () => import('@png/CH0275_home_2.png?binary'),
    'CH0275_home.png': () => import('@png/CH0275_home.png?binary'),

    'CH0238_home.skel': () => import('@skel/CH0238_home.skel?binary'),
    'CH0238_home.atlas': () => import('@atlas/CH0238_home.atlas?raw'),
    'CH0238_home_2.png': () => import('@png/CH0238_home_2.png?binary'),
    'CH0238_home.png': () => import('@png/CH0238_home.png?binary'),

    'CH0080_home.skel': () => import('@skel/CH0080_home.skel?binary'),
    'CH0080_home.atlas': () => import('@atlas/CH0080_home.atlas?raw'),
    'CH0080_home_3.png': () => import('@png/CH0080_home_3.png?binary'),
    'CH0080_home_2.png': () => import('@png/CH0080_home_2.png?binary'),
    'CH0080_home.png': () => import('@png/CH0080_home.png?binary'),

    'CH0285_home.skel': () => import('@skel/CH0285_home.skel?binary'),
    'CH0285_home.atlas': () => import('@atlas/CH0285_home.atlas?raw'),
    'CH0285_home_2.png': () => import('@png/CH0285_home_2.png?binary'),
    'CH0285_home.png': () => import('@png/CH0285_home.png?binary'),

    'CH0284_home.skel': () => import('@skel/CH0284_home.skel?binary'),
    'CH0284_home.atlas': () => import('@atlas/CH0284_home.atlas?raw'),
    'CH0284_home_2.png': () => import('@png/CH0284_home_2.png?binary'),
    'CH0284_home.png': () => import('@png/CH0284_home.png?binary'),

    'CH0281_home.skel': () => import('@skel/CH0281_home.skel?binary'),
    'CH0281_home.atlas': () => import('@atlas/CH0281_home.atlas?raw'),
    'CH0281_home_3.png': () => import('@png/CH0281_home_3.png?binary'),
    'CH0281_home_2.png': () => import('@png/CH0281_home_2.png?binary'),
    'CH0281_home.png': () => import('@png/CH0281_home.png?binary'),

    'CH0282_home.skel': () => import('@skel/CH0282_home.skel?binary'),
    'CH0282_home.atlas': () => import('@atlas/CH0282_home.atlas?raw'),
    'CH0282_home_2.png': () => import('@png/CH0282_home_2.png?binary'),
    'CH0282_home.png': () => import('@png/CH0282_home.png?binary'),

    'CH0070_home.skel': () => import('@skel/CH0070_home.skel?binary'),
    'CH0070_home.atlas': () => import('@atlas/CH0070_home.atlas?raw'),
    'CH0070_home_3.png': () => import('@png/CH0070_home_3.png?binary'),
    'CH0070_home_2.png': () => import('@png/CH0070_home_2.png?binary'),
    'CH0070_home.png': () => import('@png/CH0070_home.png?binary'),

    'CH0280_home.skel': () => import('@skel/CH0280_home.skel?binary'),
    'CH0280_home.atlas': () => import('@atlas/CH0280_home.atlas?raw'),
    'CH0280_home_2.png': () => import('@png/CH0280_home_2.png?binary'),
    'CH0280_home.png': () => import('@png/CH0280_home.png?binary'),

    'CH0158_home.skel': () => import('@skel/CH0158_home.skel?binary'),
    'CH0158_home.atlas': () => import('@atlas/CH0158_home.atlas?raw'),
    'CH0158_home_2.png': () => import('@png/CH0158_home_2.png?binary'),
    'CH0158_home.png': () => import('@png/CH0158_home.png?binary'),

    'CH0235_home.skel': () => import('@skel/CH0235_home.skel?binary'),
    'CH0235_home.atlas': () => import('@atlas/CH0235_home.atlas?raw'),
    'CH0235_home_3.png': () => import('@png/CH0235_home_3.png?binary'),
    'CH0235_home_2.png': () => import('@png/CH0235_home_2.png?binary'),
    'CH0235_home.png': () => import('@png/CH0235_home.png?binary'),

    'CH0286_home.skel': () => import('@skel/CH0286_home.skel?binary'),
    'CH0286_home.atlas': () => import('@atlas/CH0286_home.atlas?raw'),
    'CH0286_home_3.png': () => import('@png/CH0286_home_3.png?binary'),
    'CH0286_home_2.png': () => import('@png/CH0286_home_2.png?binary'),
    'CH0286_home.png': () => import('@png/CH0286_home.png?binary'),

    'CH0082_home.skel': () => import('@skel/CH0082_home.skel?binary'),
    'CH0082_home.atlas': () => import('@atlas/CH0082_home.atlas?raw'),
    'CH0082_home_2.png': () => import('@png/CH0082_home_2.png?binary'),
    'CH0082_home.png': () => import('@png/CH0082_home.png?binary'),

    'CH0197_home.skel': () => import('@skel/CH0197_home.skel?binary'),
    'CH0197_home.atlas': () => import('@atlas/CH0197_home.atlas?raw'),
    'CH0197_home_2.png': () => import('@png/CH0197_home_2.png?binary'),
    'CH0197_home.png': () => import('@png/CH0197_home.png?binary'),

    'CH0245_home.skel': () => import('@skel/CH0245_home.skel?binary'),
    'CH0245_home.atlas': () => import('@atlas/CH0245_home.atlas?raw'),
    'CH0245_home_2.png': () => import('@png/CH0245_home_2.png?binary'),
    'CH0245_home.png': () => import('@png/CH0245_home.png?binary'),

    'CH0287_home.skel': () => import('@skel/CH0287_home.skel?binary'),
    'CH0287_home.atlas': () => import('@atlas/CH0287_home.atlas?raw'),
    'CH0287_home_4.png': () => import('@png/CH0287_home_4.png?binary'),
    'CH0287_home_3.png': () => import('@png/CH0287_home_3.png?binary'),
    'CH0287_home_2.png': () => import('@png/CH0287_home_2.png?binary'),
    'CH0287_home.png': () => import('@png/CH0287_home.png?binary'),

    'CH0259_home.skel': () => import('@skel/CH0259_home.skel?binary'),
    'CH0259_home.atlas': () => import('@atlas/CH0259_home.atlas?raw'),
    'CH0259_home_3.png': () => import('@png/CH0259_home_3.png?binary'),
    'CH0259_home_2.png': () => import('@png/CH0259_home_2.png?binary'),
    'CH0259_home.png': () => import('@png/CH0259_home.png?binary'),

    'CH0288_home.skel': () => import('@skel/CH0288_home.skel?binary'),
    'CH0288_home.atlas': () => import('@atlas/CH0288_home.atlas?raw'),
    'CH0288_home_2.png': () => import('@png/CH0288_home_2.png?binary'),
    'CH0288_home.png': () => import('@png/CH0288_home.png?binary'),

    'CH0242_home.skel': () => import('@skel/CH0242_home.skel?binary'),
    'CH0242_home.atlas': () => import('@atlas/CH0242_home.atlas?raw'),
    'CH0242_home_3.png': () => import('@png/CH0242_home_3.png?binary'),
    'CH0242_home_2.png': () => import('@png/CH0242_home_2.png?binary'),
    'CH0242_home.png': () => import('@png/CH0242_home.png?binary'),

    'CH0243_home.skel': () => import('@skel/CH0243_home.skel?binary'),
    'CH0243_home.atlas': () => import('@atlas/CH0243_home.atlas?raw'),
    'CH0243_home_3.png': () => import('@png/CH0243_home_3.png?binary'),
    'CH0243_home_2.png': () => import('@png/CH0243_home_2.png?binary'),
    'CH0243_home.png': () => import('@png/CH0243_home.png?binary'),

    'CH0257_home.skel': () => import('@skel/CH0257_home.skel?binary'),
    'CH0257_home.atlas': () => import('@atlas/CH0257_home.atlas?raw'),
    'CH0257_home_3.png': () => import('@png/CH0257_home_3.png?binary'),
    'CH0257_home_2.png': () => import('@png/CH0257_home_2.png?binary'),
    'CH0257_home.png': () => import('@png/CH0257_home.png?binary'),

}
export default resourceLoader;